print("halo sayang aku")
print("persija day")
print("jangan lupa makan")
print("semangat buat kamu")
print("selamat ulangtahun")
print("boleh kenalan gak")
print("selmat pagi")
print("bismillah sukses")
print("sehat terus kawan")
print("hati hati di jalan")
